application: biafra1973
version: 4
runtime: python
api_version: 1

handlers:

- url:  /_ah/xmpp/message/chat/
  script: chat.py

- url:  /_ah/xmpp/message/available/
  script: chat.py

- url: /.*
  script: main.py

inbound_services:
- mail
- warmup
- xmpp_message
#- xmpp_presence
#- xmpp_subscribe